const languageDict = {
  Chinese: {
    Auto: "自动检测",
    English: "英语",
    Catalan: "加泰语",
    Spanish: "西班牙语",
    Chinese: "中文",
    French: "法语",
    German: "德语",
    Italian: "意大利语",
    Portuguese: "葡萄牙语",
    Japanese: "日语",
    Korean: "韩语",
    Arabic: "阿拉伯语",
    Russian: "俄语",
    prompt: "提示词",
    input: "按下 Ctrl+T 从剪贴板粘贴...",
    keymissing: "缺少API密钥, 请在选项内填入",
    failedrequest: "请求失败, 请检查网络和API密钥",
    title: "openAI 密钥",
    keyplaceholder: "API 密钥",
  },
  English: {
    Auto: "Auto Detect",
    English: "English",
    Catalan: "Catalan",
    Spanish: "Spanish",
    Chinese: "Chinese",
    French: "French",
    German: "German",
    Italian: "Italian",
    Portuguese: "Portuguese",
    Japanese: "Japanese",
    Korean: "Korean",
    Arabic: "Arabic",
    Russian: "Russian",
    prompt: "Prompt",
    input: "Press Ctrl+T to paste from clipboard...",
    keymissing: "Missing API key, please fill in the options",
    failedrequest: "Request failed, please check your network and API key",
    title: "OpenAI Key",
    keyplaceholder: "API Key",
  },
  Spanish: {
    Auto: "Auto Detectar",
    English: "Inglés",
    Catalan: "Catalán",
    Spanish: "Español",
    Chinese: "Chino",
    French: "Francés",
    German: "Alemán",
    Italian: "Italiano",
    Portuguese: "Portugués",
    Japanese: "Japonés",
    Korean: "Coreano",
    Arabic: "Árabe",
    Russian: "Ruso",
    prompt: "Prompt",
    input: "Presiona Ctrl+T para pegar desde el portapapeles...",
    keymissing: "Falta la clave API, por favor llene las opciones",
    failedrequest:
      "La solicitud ha fallado, por favor verifique su red y clave API",
    title: "Clave de OpenAI",
    keyplaceholder: "Clave de API",
  },
};

module.exports = languageDict;
